### PR TITLE
search's cleared event is fired when field is empty #931

### PR DESCRIPTION
**Pull request by BenjaminNeilDavis**
- added an option to clear when input is empty (by default set to false)
- worked with the search / close icon to make more sense
- When already searched a value the icon turns to a x. The change i implemented is if the input value changes the icon turns back to a search icon. Before it would stay an x and would have to click enter to search a different value.

### CODE REVIEW

**Comment by interactivellama** [comment]
That third bullet is a great UX find.

**Comment by interactivellama** [comment]
After I clear the field, the icon goes back to search, but when I tab back into the input field. The clear icons appears again even though the field is blank. (last frame of screen capture below)

**Comment by swilliamset** [comment]
@BenjaminNeilDavis please update your branch so the PR can be merged.

**Comment by BenjaminNeilDavis** [comment]
Working on the fix now...great catch

**Pull request merged**
