### PR TITLE
Fix width when using images within selectlist

### PR DESCRIPTION
**Pull request by scott-joe**
My terminal is borked so you'll have to check the solution, but I just did what you suggested in the issue thread #1463

### CODE REVIEW

**Comment by futuremint** [comment]
Please ensure that this fix is _actual_ and not _probable_.  Once you're sure this _is the fix_, we'll review it.

**Comment by swilliamset** [comment]
hold until full validation as suggested by woodward above

**Comment by cormacmccarthy** [comment]
image

Selectlist resizes vertically as well as horizontally. @jamin-hall is this desired? Or should it be vertically static?

**Comment by cormacmccarthy** [comment]
Needs some vertical alignment love.

**Pull request closed without merging**
