### PR TITLE
(gh-pages) Removed extra wrapper causing double events

### LINKED ISSUE #1188: datepicker examples broken in documentation
Datepicker skips months (previous, next)
http://getfuelux.com/javascript.html#datepicker

Method buttons not working correctly

### PR DESCRIPTION
**Pull request by Alondite00**
Fixes #1188

### CODE REVIEW

**Comment by swilliamset** [comment]
Tab in once to remove the extra whitespace and then i'll merge

**Comment by swilliamset** [comment]
Yes the container element is outside of this file. I've verified locally the bug and the fix provided here.

**Comment by mbeard** [comment]
Good deal...just checking.  Thanks.

**Comment by swilliamset** [comment]
https://github.com/Alondite00/fuelux/blob/4879507251f944b1ebd7e7edc6571a573fcee45a/_includes/js/datepicker.html#L8

**Pull request merged**
