### PR TITLE
license file listed the company as ExactTarget

### PR DESCRIPTION
**Pull request by rbmoore**

### CODE REVIEW

**Comment by cormacmccarthy** [comment]
We still haven't been given the greenlight from legal to change this, correct? Or did you hear something different? Last time we asked we were told to leave it as ExactTarget was my impression...

**Comment by rbmoore** [comment]
I was adding the the license file to an internal project and noticed it was still showing ET.  The readme file calls us "Salesforce Marketing Cloud, Inc." at the bottom, so I put in the pull request.  Didn't know this was waiting on lawyers to gift us filthy developers with their pious wisdom.

**Comment by cormacmccarthy** [comment]
The official un-official word on the street is, "we have not been directed to update our license agreement AFAIK, so i don't think it needs to be changed at this time". :grimacing:

**Comment by interactivellama** [comment]
Yes, I can confirm. That we are ExactTarget legally, but Salesforce everywhere else (readme, etc).

**Comment by rbmoore** [comment]
would you at least like the year bumped to 2015 in the readme and license?

**Comment by interactivellama** [comment]
That'd be great. Thanks, @rbmoore.

**Pull request closed without merging**
