### PR TITLE
Form builder audit

### PR DESCRIPTION
**Pull request by cormacmccarthy**
This is an audit of the form builder as it currently exists (It does not attempt add additional components and controls, but rather is intended to ensure that the markup and attributes of the currently available controls are correct and complete).

Output generated by Form Builder for testing:

Horizontal (widen results pane to see horizontal --it's responsive)
http://jsfiddle.net/cmcculloh/znc5vjj0/
http://jsfiddle.net/yop3yLbw/1/ (mctheme version)

Normal:
http://jsfiddle.net/cmcculloh/yop3yLbw/
http://jsfiddle.net/yop3yLbw/2/ (mctheme version)

### CODE REVIEW

**Comment by swilliamset** [comment]
The template work here will assist in getting closer to https://github.com/ExactTarget/fuelux/issues/1154

**Comment by kevinparkerson** [comment]
A cursory glance at the code here looks ok to me.

**Comment by kevinparkerson** [comment]
Oh shoot, so I checked MCtheme... @cormacmccarthy, checkbox addon looks weird with MCtheme on the fiddle:

http://jsfiddle.net/yop3yLbw/1/ (mctheme version)
http://jsfiddle.net/yop3yLbw/2/ (mctheme version)

That might be resolved with the latest fuelux version, though perhaps MC theme needs to be updated to compliment the latest release.

**Comment by kevinparkerson** [comment]
@cormacmccarthy additional minor thing - for the dropdown with the action button on the right side, perhaps the drop-menu should have `pull-right`, in order to make the menu right aligned with the button. That way it won't go off the page if it's far to the right, as it does now

**Comment by cormacmccarthy** [comment]
@kevinparkerson The Form Builder uses the new correct markup for checkbox addon. MC Theme has an accepted PR to support this, but, we need an MC Theme release to get it out there (So, yes, MC Theme has been updated to compliment the latest release, but, that update hasn't "gone live" yet).

**Comment by cormacmccarthy** [comment]
Thanks added `pull-right`

**Pull request merged**
