### PR TITLE
Multiply occurrence by days if weekly frequency

### LINKED ISSUE #1450: Scheduler not RFC 2445 compliant - weekly repetition
The scheduler is producing a RRule that is not RFC 2445 compliant when using a weekly repetition with more than one day. Using the example: Weekly on Tuesday and Thursday for 5 weeks: the RRULE generated would be: FREQ=WEEKLY;COUNT=5;WKST=SU;BYDAY=TU,TH;

From the RFC document: https://tools.ietf.org/html/rfc2445 it should be:
DTSTART;TZID=US-Eastern:19970902T090000 RRULE:FREQ=WEEKLY;COUNT=10;WKST=SU;BYDAY=TU,TH
==> (1997 9:00 AM EDT)September 2,4,9,11,16,18,23,25,30;October 2

The difference is the COUNT parameter. There's also a unsupported trailing semicolon that some RFC 2445 parsers will have trouble with.

### PR DESCRIPTION
**Pull request by interactivellama**
Fixes #1450

> The COUNT rule part defines the number of occurrences at which to range-bound the recurrence.

### CODE REVIEW

**Comment by swilliamset** [comment]
Why are we holding?

**Comment by interactivellama** [comment]
I need time to understand the verbose spec. Corwin and I tested the pattern in iCal and it works the current way that our Scheduler works--that is `count` is not a multiple of weekly, it is the actual number of occurrences.

Either Apple iCal is implemented wrong or I don't understand the spec.

**Comment by swilliamset** [comment]
I think iCal is correct. Lets discuss further offline.

**Comment by interactivellama** [comment]
Also, this could a user understanding issue, too. Like what is an occurrence?

```
Weekly on Tuesday and Thursday for 5 weeks:

 DTSTART;TZID=US-Eastern:19970902T090000
 RRULE:FREQ=WEEKLY;UNTIL=19971007T000000Z;WKST=SU;BYDAY=TU,TH
 or
 RRULE:FREQ=WEEKLY;COUNT=10;WKST=SU;BYDAY=TU,TH

 ==> (1997 9:00 AM EDT)September 2,4,9,11,16,18,23,25,30;October 2
```
from http://www.kanzaki.com/docs/ical/rrule.html

The count is certainly the total, but is `count` the same as occurrence? This may be a UI affordance issue and not a parsing issue.

**Comment by interactivellama** [comment]
See https://github.com/ExactTarget/fuelux/issues/1450#issuecomment-131907515

**Comment by interactivellama** [comment]
Based on Google and Apple's Calendar implementation, and the informal survey of user perception of our UX department designers and researchers, I recommend we close this PR and not change "the code," but change the markup and add the additional label of the Weekly button group to "Repeats on" to add clarity.

**Pull request closed without merging**
