### PR TITLE
Fix checkbox markup in example page to have span

### LINKED ISSUE #1381: Checkbox has no style change on focus
There is a style change on hover, but not focus.

### PR DESCRIPTION
**Pull request by interactivellama**
The `index.html` checkbox markup was incorrect. Fixes #1381.

### CODE REVIEW

**Comment by kevinparkerson** [comment]
@interactivellama the grey-ification on tabbing is back! although it's somewhat hard to see... perhaps we add the hover box-shadow effect too? (if possible)

**Comment by interactivellama** [comment]
The issue is that the input has the focus and it is a child of the label. There is no CSS parent selector. The hover is able to affect the input, but the input cannot affect the label, just the span which is its sibling.

**Comment by swilliamset** [comment]
Is this resolved and ready to be merged or on hold?

**Comment by interactivellama** [comment]
@swilliamset This is a revert to a previous state that got overwritten. The hover suggestion by @kevinparkerson is not possible with CSS only due to the lack of a reverse sibling selector.

**Pull request merged**
