### PR TITLE
Remove custom build step for wrapping with UMD

### PR DESCRIPTION
**Pull request by gtanner**
Since the UMD boilerplate code was duplicated and then stripped out in all of the files in the `js` folder, it makes more sense to wrap each individual file and place the wrapped version in the  `dist` folder.

This cleans up the build / code and places all of the usable files into the `dist` folder (rather then being a mix between the `js` and `dist` folders.

### CODE REVIEW

**Comment by gtanner** [comment]
Should https://github.com/gtanner/fuelux/blob/master/js/all.js still exist?  Seems to be replaced by `dist/js/fuelux.js`

**Comment by interactivellama** [comment]
`all.js` is legacy from version 2.x in case developers were still using it in their AMD bundling. It should be deprecated and removed, especially since the files in `/js' are no longer going to be AMD compatible anyway. @kevinparkerson @swilliams

**Comment by interactivellama** [comment]
Connected to issue #1168.

**Comment by interactivellama** [comment]
The current QUnit tests use AMD and point to `js` folder. Removing UMD wrapper will cause these unit tests to fail. This is most likely the issue with TravisCI.

**Comment by gtanner** [comment]
I ran the tests locally and they passed:

I had updated the tests to run from dist: https://github.com/ExactTarget/fuelux/pull/1169/files#diff-3e4cf9e18249a1342b633a8183aa8040R55.  

was this what you were referencing?
```
gtanner@Gords-MacBook-Pro:~/Projects/fuelux (master)$ grunt test
Running "jshint:sourceAndDist" (jshint) task
>> 20 files lint free.

Running "jshint:tests" (jshint) task
>> 21 files lint free.

Running "connect:testServer" (connect) task
Started connect web server on http://0.0.0.0:9000

Running "blanket_qunit:source" (blanket_qunit) task
Testing http://localhost:9000/test/?coverage=true&gruntReport.......................................................................................................................................................................................................................

Per-File Coverage Results: (1% minimum)
PASS : 18 files passed coverage

Global Coverage Results: (1% minimum)
PASS [ 82%] : global (2768 / 3360)

Unit Test Results: 616 tests passed (6901ms)

>> No issues found.

Running "qunit:noMoment" (qunit) task
Testing http://localhost:9000/test/?no-moment=true ...............OK
>> 40 assertions passed (139ms)

Running "qunit:globals" (qunit) task
Testing http://localhost:9000/test/browser-globals.html .................OK
>> 17 assertions passed (27ms)

Running "validation:files" (validation) task
Validation started for.. index.html

Done, without errors.
```

**Comment by gtanner** [comment]
I did notice this in the travis logs:

```
Registering "grunt-umd" local Npm module tasks.
>> Local Npm module "grunt-umd" not found. Is it installed?
```

**Comment by gtanner** [comment]
Hey @interactivellama,

seems the problem is the new npm dep isn't installed.  

https://github.com/ExactTarget/fuelux/blob/master/.travis.yml#L5-L7

how do we get the new deps to show up there?

**Comment by gtanner** [comment]
Would the real fix be to run ```npm install``` rather then ```wget``` off your heroku?

**Comment by interactivellama** [comment]
You are right. `npm install` is unreliable in our experience (we've had to restart TravisCI many times), so any new modules have to be published to the Heroku site first. I can do this.

**Comment by cormacmccarthy** [comment]
FYI: I am currently working on this. There are some other changes/refinements we want to make alongside this. I'll probably end up opening a new PR (based off of this one) and close this one in favor of that (your commits will still "go in" they'll just have a bunch more on top of them. Otherwise, I'll have to PR to you to have you update this PR, and that just seems a little silly?).

**Comment by gtanner** [comment]
Sounds good to me :)

**Comment by gtanner** [comment]
Hey ... anything I can help with to get this going again?

**Comment by cormacmccarthy** [comment]
It didn't stop, there's just a _lot_ going on behind the scenes. I'm hoping to have it all ready EOD today though. Thanks!

**Comment by cormacmccarthy** [comment]
@gtanner this is happening and I can't explain it:

image

Any thoughts?

If this gets sorted out, only thing left to do is move all the grunt config stuff into its own file and then this will all be ready to merge.

I'd love to make the handlebars umd wrapper stuff rip the jquery closure out of each file before shoving it into the umd closure/wrapper, but, that's not a show-stopper...

**Comment by cormacmccarthy** [comment]
This was the next step (or something like this) as either part of this effort, or immediately following this effort:

https://github.com/creynders/load-grunt-configs

**Comment by gtanner** [comment]
Wow, I have no idea @cormacmccarthy.

Was that a "first build" vrs a "second build"?  wondering if there is something missing from the first time the build step runs

**Comment by cormacmccarthy** [comment]
@interactivellama has indicated this may be due to some sort of "race conditions". I'm hoping to be able to get back to this sometime next week if no one else has made any progress by then.

**Comment by swilliamset** [comment]
closing ticket un

**Comment by swilliamset** [comment]
@gtanner @cmcculloh @interactivellama 
closing ticket until an update is provided

**Comment by swilliamset** [comment]
@interactivellama since changing our module structure does this change?

**Pull request closed without merging**
