### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by vernak2539** [comment]
This is required for the "bower badge" in the readme file. will not remove

**Comment by vernak2539** [comment]
Actually,

> Version badge uses GitHub tags to identify the latest Bower version. Please use Semantic Version tags to ensure proper badge function.

This is valid. not sure the bower version is used for anything

**Comment by kkirsche** [comment]
It's not, hence the PR. Also just an FYI there are discussions to move bower to NPM anyway so I wouldn't really plan to support it for ever: bower/bower#1520

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by interactivellama** [comment]
We modify the `bower.json` file via the `replace` task in `gruntFile.js` at every release, so that task needs to be modified too.

**Comment by swilliamset** [comment]
The following line will need to be updated to no longer attempt to bump the version in the bower file

https://github.com/ExactTarget/fuelux/blob/master/Gruntfile.js#L28

@kkirsche would you be willing to update the PR

**Comment by kkirsche** [comment]
@swilliamset done

**Comment by swilliamset** [comment]
Looks like we have a conflict now. Could you rebase? If not totally understand we'll handle it. Thanks for the heads up.

**Comment by kkirsche** [comment]
@swilliamset yeah it was cause you guys issued another release since this was made. I've rebased and squashed cause, well, why not

**Comment by swilliamset** [comment]
squashes are always greatly appreciated. once travis finishes i'll be glad to merge. thanks again.

**Pull request merged**
