### PR TITLE
Gh1121   make tree.openfolder only open folders instead of toggling them

### LINKED ISSUE #1121: Make tree.openFolder only open folders instead of toggling them
the `openFolder` method on the `tree` is misnamed, it is actually a toggle. Issue #1105 created a `toggleFolder` method, but in order to not be a breaking change it kept `openFolder`'s behavior as being "toggle" unless you set your options object to `{ignoreRedundantOpens: true}`.

This issue is to remove that from the `openFolder` method so that `openFolder` truly just opens the folder by default.

### PR DESCRIPTION
**Pull request by cormacmccarthy**
fixes #1121

### CODE REVIEW

**Comment by interactivellama** [comment]
Reviewed, but should wait until 3.7 release to merge due to an API breaking change.

**Comment by cormacmccarthy** [comment]
:+1:

**Comment by swilliamset** [comment]
@cormacmccarthy or @interactivellama please rebase and retest so able to merge

**Comment by interactivellama** [comment]
@cormacmccarthy I originally cloned this down and phantomJS timed out. I thought it was my setup and so I ran the tests again and they all passed, so I merged. Do you know if there is a history of test fails with usage of `disclose`. Should we put a counter/limit on our test datasource to prevent time outs?

https://travis-ci.org/ExactTarget/fuelux/builds/58018262#L588

**Pull request merged**
