### PR TITLE
Added data-name for selectedItem

### PR DESCRIPTION
**Pull request by swbullis**
Added Ability to change step based on data-name of the wizard pane instead of just step id.

### CODE REVIEW

**Comment by futuremint** [comment]
Please add some unit tests to test this additional functionality.  See step 1 from [our contribution steps](https://github.com/ExactTarget/fuelux/wiki/Contributing-to-Fuel-UX#basic-steps).  Thanks.

**Comment by futuremint** [comment]
@swbullis please add unit tests to this so that we can consider merging this or not.  Thanks.

**Comment by cormacmccarthy** [comment]
fixes #607 

@swbullis thank you for your contribution and interest. Let me know if you need some help figuring out the unit test stuff.

**Comment by swilliamset** [comment]
closing while waiting for unit test

**Comment by cormacmccarthy** [comment]
I need to be able to clone it to add the unit tests, which I don't know how to do while it is closed.

**Pull request closed without merging**
