### PR TITLE
Radio button refactor

### PR DESCRIPTION
**Pull request by mbeard**
Refactor of the radio control.

### CODE REVIEW

**Comment by swilliamset** [comment]
@mbeard please rebase to resolve merge conflict

**Comment by swilliamset** [comment]
@sjames include undocumented methods no longer available in the release notes

**Comment by interactivellama** [comment]
The following *undocumented* public methods have been removed from radio:
setState, toggleContainer

Additionally, the radio and checkbox controls are now bound to the parent element with the respective `.radio` and `.checkbox` classes and no longer to the `<input>` element.

@mbeard Anything else that you would like to see in the release notes?

**Comment by chriscorwin** [comment]
Went to review this, there's significant diffs from the latest master.

@mbeard can you pull latest from upstream and merge master in then re-submit this?

**Comment by mbeard** [comment]
@chriscorwin done

**Comment by chriscorwin** [comment]
Cool... except now the radio highlighting isn't working, similar to how checkbox isn't in its branch.

I have tweaked the rules, and uploaded what `radio.less` should be to a gist, here:

https://gist.github.com/chriscorwin/63ef5e32609ef677c2ef

Put that into place and I think we're golden.

**Pull request merged**
