### PR TITLE
Checkbox refactor

### PR DESCRIPTION
**Pull request by mbeard**
Refactoring of checkbox

### CODE REVIEW

**Comment by mbeard** [comment]
I disagree.  We shouldn't support setting the checked appearance without setting the checked state.  Why would we ever want those to be out of sync.  Same for disabled.

**Comment by swilliamset** [comment]
My statement was assuming the function setting the class would insure the control state was synced but i see how the existing function name could cause that confusion.

**Comment by swilliamset** [comment]
@sjames include undocumented methods no longer available in the release notes

**Comment by interactivellama** [comment]
The following *undocumented* public methods have been removed from checkbox:
setState, _toggleCheckedState, _toggleDisabledState, _setDisabledClass, and _setCheckedClass 

Additionally, the radio and checkbox controls are now bound to the parent element with the respective `.radio` and `.checkbox` classes and no longer to the `<input>` element.

@mbeard Anything else that you would like to see in the release notes?

**Comment by chriscorwin** [comment]
Highlight isn't working.

The rule to add the background needs changed.

Right here:

https://github.com/mbeard/fuelux/blob/master/less/checkbox.less#L16


...change it to this:

`&.checked label.checkbox-custom, label.checked.checkbox-custom {`

**Pull request merged**
