### PR TITLE
[Pillbox]: Fixed no binding suggested.fu.pillbox when load fuelux in html head section

### PR DESCRIPTION
**Pull request by afz**
Hi,

document.body not defined when load fuelux in page head section

### CODE REVIEW

**Comment by swilliamset** [comment]
hi @afz could you please update your branch and provide some more details in your issue. 

also the [PR template](https://github.com/ExactTarget/fuelux/blob/master/.github/PULL_REQUEST_TEMPLATE.md) has some great guidelines to help get your PR merged faster.

**Comment by afz** [comment]
Hi,
if you put fuelux to html head section:
<head>
...
<script type="text/javascript" src="fuelux/js/fuelux.min.js"></script>
</head>

event "suggested.fu.pillbox" not bind because document.body return undefined.

**Comment by afz** [comment]
any news?!

**Comment by swilliamset** [comment]
you've changed the line ending whitespace to your modified files. please correct.

**Pull request closed without merging**
