### PR TITLE
Allows for wizard to go RTL

### LINKED ISSUE #1156: can i use Fuel UX - Wizard from Right to Left

### PR DESCRIPTION
**Pull request by vernak2539**
fixes #1156.

All they have to do is add a class of "rtl" next to wizard. Example of markdown can be found [here](https://gist.github.com/vernak2539/e8e4a9226115a4e042cf)

### CODE REVIEW

**Comment by aziz1117** [comment]
i try to write "RTL" next to "Wizard" but it still from Left to Right, could you please explain how to do that.

**Comment by vernak2539** [comment]
@aziz1117 without this being merged in it's a little tougher. Once this is merged, you can probably model your markdown after the example link in the original comment.

Otherwise, you can compile the diff in the LESS and add it to an extra stylesheet

**Comment by vernak2539** [comment]
@swilliamset @cormacmccarthy anyone have time to look at this? It's a pretty simple change, but has just been sitting here

**Comment by swilliamset** [comment]
wizard-rtl

The content and the steps (name number, name number, etc) look correct but not 100% on what should be expected from the next/prev buttons.

Do we have requirements or a user story that we can sync with?

**Comment by vernak2539** [comment]
Nope, it was just a random thing after I saw that issue.

The buttons behaviours are mirrored exactly and I provided an example of
what the markup should be

**Comment by vernak2539** [comment]
@swilliamset I don't think you're using the markdown example I put in the original comment. Please use that one, and it should be correct

**Comment by swilliamset** [comment]
@vernak2539 you are exactly right i took
> All they have to do is add a class of "rtl"
to mean that was the only change to the markdown.

also i'm seeing some sensitivity in firefox where the content slides under the header. @vernak2539 can you reproduce?

**Comment by vernak2539** [comment]
I'll take a look in a bit

**Comment by swilliamset** [comment]
on resize or monitor change even it corrects itself :(

screen shot 2015-03-13 at 2 28 59 pm

**Comment by cormacmccarthy** [comment]
Do we control the fact that the next and prev arrows are pointed in the wrong direction, or is that something we expect users(developers) to "worry" about?

**Comment by swilliamset** [comment]
The markup needs to be moved as the link at the top shows. Already discussed with Alex. Will need to be well documented with the snippet provided.

**Comment by vernak2539** [comment]
@swilliamset I wasn't able to reproduce in firefox. Attached a screenshot. Tried resizing the window before and after loading to no avail. 
wizard rtl

**Comment by swilliamset** [comment]
I'm on 36.0.4. As mentioned in your about there is an update.

**Comment by vernak2539** [comment]
Damn, who thought two minor versions would make that happen. will look into it

**Comment by swilliamset** [comment]
them be major version son!

**Comment by vernak2539** [comment]
Shit, brain wasn't working. You're right

**Comment by swilliamset** [comment]
@vernak2539 any updates on this?

**Comment by vernak2539** [comment]
I haven't had the time. I'll try to get to it this week

**Comment by vernak2539** [comment]
This is good to go.

screen shot 2015-04-17 at 1 35 37 pm


I've added a more detailed example gist [here](https://gist.github.com/vernak2539/dd491213fde859f6a96c)

**Comment by swilliamset** [comment]
:tada: :balloon: :tada: finally merged :tada: :balloon: :tada: 
thx @vernak2539

**Comment by vernak2539** [comment]
:+1:

**Comment by vernak2539** [comment]
@swilliamset what release is this going into?

**Comment by swilliamset** [comment]
targeting 3.8.0. based on internal calendars we are reserving the next minor release untill June 1st at the latest.

**Comment by vernak2539** [comment]
No worries. Just was wondering since it was merged into master and the 3.7.3 release happened, but there was no link to the issue in the release notes. So I assume it will be in master, then "released" with 3.8?

**Pull request merged**
